music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    #/music/
    path('', views.IndexView.as_view(), name='index'),
    #/music/<album_id>/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

music/models.py
from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + '-' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.views import generic
from .models import Album

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

music/templates/music/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Acoustic{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css2?family=Norican&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar  navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                   <!-- Logo -->
                       <a class="navbar-brand" href="{% url 'music:index' %}">Acoustic</a>
                       <button  type="button" class="navbar-toggler " data-toggle="collapse" data-target="#topNavBar" aria-expanded="false">
                           <span id="toolbar" class="navbar-toggler-icon"></span>
                       </button>
                   <div class="collapse navbar-collapse" id="topNavBar">
                       <!---Items-->
                       <ul class="navbar-nav">
                           <li class="nav-item">
                               <a href="{% url 'music:index' %}">
                                   <span class="fas fa-compact-disc" aria-hidden="true"></span>&nbsp; Albums
                               </a>
                           </li>
                           <li class="nav-item">
                               <a href="#">
                                   <span class="fab fa-itunes-note" aria-hidden="true"></span>&nbsp; Songs
                               </a>
                           </li>
                       </ul>
                       <form class="form-inline" role="search" method="get" action="#">
                           <div class="form-group">
                               <input type="text" class="form-control mr-sm-2" placeholder="Search" name="q" value="">
                           </div>
                           <button type="submit" class="btn btn-light">Search</button>
                       </form>
                       <ul class="navbar-nav navbar-right">
                            <li class="nav-item">
                                <a href="#">
                                    <span class="fas fa-plus" aria-hidden="true"></span>&nbsp; Add Album
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#">
                                    <span class="fas fa-power-off" aria-hidden="true"></span>&nbsp; Logout
                                </a>
                            </li>
                       </ul>
                   
                    </div>
               </div>
           </nav>
           {% block body %}
           {% endblock %}
    </body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}

{% block body %}
    <img src="{{ album.album_logo }}">

    <h1>{{ album.album_title }}</h1>
    <h3>{{ album.artist }}</h3>

    {% for song in album.song_set.all %}
        {{ song.song_title }}
        {% if song.is_favorite %}
            <img src="https://findicons.com/files/icons/1588/farm_fresh_web/16/bullet_star.png" />
        {% endif %}
        <br>
    {% endfor %}

{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}

    <ul>
        {% for album in all_albums %}
            <li><a href=" {% url 'music:detail' album.id %} ">{{ album.album_title }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}    